kind: pipeline
volumes:
  - name: node_modules
    host:
      path: /root/node-service/node_modules
  - name: ssh_keys
    host:
      path: /root/.ssh
clone:
  disable: true

steps:
  - name: feishu
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/foo-webhook
    settings:
      webhook:
        from_secret: webhook
      secret:
        from_secret: secret
      text: hello

  - name: clone
    image: alpine/git
    volumes:
      - name: ssh_keys
        path: /root/.ssh
    environment:
      warehouse_name: node-service

    commands:
      - echo $DRONE_GIT_SSH_URL
      - ls /root/.ssh/
      - chmod -R 600 /root/.ssh/
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - git clone -b $DRONE_COMMIT_BRANCH --depth=1 $DRONE_GIT_SSH_URL
      - cd $warehouse_name
      - pwd
      - mv -f * .[^.]* /drone/src
      - ls

  - name: build
    image: node
    depends_on: [clone]
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - pwd
      - ls -a
      - npm install
      - npm run build
      - ls -a

  - name: deploy
    image: appleboy/drone-scp
    depends_on: [build]
    settings:
      host:
        from_secret: server_host
      port: 22
      username:
        from_secret: username
      password:
        from_secret: server_password
      overwrite: true
      target: /root/node-service
      source:
        - dist
        - .npmrc
        - package.json
        - pnpm-lock.yaml
        - bootstrap.js
        - tsconfig.json

  - name: ssh
    image: appleboy/drone-ssh
    depends_on: [ deploy ]
    settings:
      host:
        from_secret: server_host
      username:
        from_secret: username
      password:
        from_secret: server_password
      port: 22
      command_timeout: 2m
      script:
        - echo "Hello World"
        - cd /root/node-service
        - pnpm i
        - pm2 del node-service
        - pm2 start npm --name node-service -i max -- run "start"
