kind: pipeline
type: docker
name: ci/cd
volumes:
  - name: node_modules
    host:
      path: /root/drone/node-service/node_modules
clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir $HOME/.ssh
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git init
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch
      - git checkout origin/$DRONE_COMMIT_BRANCH -ft
  - name: build
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/pnpm
    depends_on:
      - clone
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - node -v
      - pnpm -v
      - pnpm install
      - pnpm run build
  - name: deploy
    image: appleboy/drone-scp
    depends_on:
      - build
    settings:
      host:
        from_secret: server_host
      port: 22
      username:
        from_secret: username
      password:
        from_secret: server_password
      overwrite: true
      target: /root/node-service
      source:
        - dist
        - .npmrc
        - package.json
        - pnpm-lock.yaml
        - bootstrap.js
        - tsconfig.json
  - name: ssh
    image: appleboy/drone-ssh
    depends_on:
      - deploy
    settings:
      host:
        from_secret: server_host
      username:
        from_secret: username
      password:
        from_secret: server_password
      port: 22
      command_timeout: 2m
      script:
        - cd /root/node-service
        - pnpm i --frozen-lockfile
        - pm2 del node-service
        - pm2 start npm --name node-service -i max -- run start
